spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydbDev
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
     ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/